### ISSUE TITLE
Number of Cell with a specific gene expressed per cluster. How?

### ISSUE THREAD

**Issue by Fdm8610** [broadinstitute/single_cell_portal_core#1609]
I would like to count how many cells per defined clusters expressed a specific gene of interest. I can see violin plot/bar plot with data points, but how to count those cells compared to total cells in the cluster?

Thank you very much for your help

F

**Comment by eweitz** [comment]
Thanks for also contacting us via [scp-support@broadinstitute.zendesk.com](mailto:scp-support@broadinstitute.zendesk.com)!  (That support email address is usually the fastest and surest way to get in touch with the SCP team about feature requests, product bugs, questions, etc.)

We've picked this up over in https://broadinstitute.zendesk.com/agent/tickets/294251, so I'll go ahead and close this issue.
