### ISSUE TITLE
Getting error on building the Single Cell Portal image

### ISSUE THREAD

**Issue by chees01** [broadinstitute/single_cell_portal_core#43]
Getting the follow error on building the Single Cell Portal image using: docker build -t single_cell_docker -f Dockerfile .

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory:
/usr/local/rvm/gems/ruby-2.3.1/gems/nokogiri-1.6.7.2/ext/nokogiri
/usr/local/rvm/rubies/ruby-2.3.1/bin/ruby -r ./siteconf20171108-5-1ssw318.rb

The source files are download today (11/8/17).  The Docker is running on centos-release-7-2.1511.el7.centos.2.10.x86_64..

Any insights or suggestions?

Thanks,

Esther

**Comment by bistline** [comment]
Esther -

We use Ubuntu 15.10 and 16.04 for our Docker deployments (and use Docker for Mac OSX locally), so I don't have any experience with a CentOS build.  Having said that, the whole point of Docker is that it is portable, so the build failure is perplexing.  The host OS shouldn't matter for gem installations.

Unfortunately, this isn't really an issue with the portal itself, but rather with Docker on a CentOS machine, so I don't have much insight into this kind of issue.  You may want to look at the mkmf.log file for that particular installation to see if there are any clues in there.

Jon

**Comment by chees01** [comment]
Thanks for quick reply.  I  looked at mkmf.log file, the checking for ruby_version returns “no” .  Does it require ruby installed on the system before building the Single Cell Portal image…?  But the setup doc stated that “the image is built off of the Passenger-docker baseimage and comes with Ruby, Nginx, and Passenger by default…”

have_var: checking for ruby_version... -------------------- no

"gcc -I/usr/local/rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/x86_64-linux -I/usr/local/rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/ruby/backward -I/usr/local/rvm/rubies/ruby-2.3.1/include/ruby-2.3.0 -I/usr/share/passenger/ruby_extension_source     -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -Wno-maybe-uninitialized  -fPIC -g   -c conftest.c"
conftest.c: In function 't':
conftest.c:13:55: error: 'ruby_version' undeclared (first use in this function)
int t(void) { const volatile void *volatile p; p = &(&ruby_version)[0]; return !p; }
                                                       ^
conftest.c:13:55: note: each undeclared identifier is reported only once for each function it appears in
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: /*top*/
4: extern int t(void);
5: int main(int argc, char **argv)
6: {
7:   if (argc > 1000000) {
8:     printf("%p", &t);
9:   }
10:
11:   return 0;
12: }
13: int t(void) { const volatile void *volatile p; p = &(&ruby_version)[0]; return !p; }
/* end */

Thanks for your help,

Esther

**Comment by bistline** [comment]
So it does require Ruby to be installed, but you are correct in that the Phusion Passenger Docker image comes with multiple versions of Ruby installed, so I'm not sure why it wouldn't find Ruby for you.  We've never had that issue with our containers.  You may want to file a ticket with them instead as they'll be able to help better.
