### ISSUE TITLE
Enable admin account:  getting "NoMethodError: undefined method `update' for nil:NilClass"

### ISSUE THREAD

**Issue by chees01** [broadinstitute/single_cell_portal_core#49]
Getting the following error on enable admin user accounts in rails console.  It looks like there is no user with the email that I specified.  Do I need to create the admin user before enable it?   Thanks,  Esther

chees01@ndhsinnl145:~/project/single_cell_portal_core-master$ docker exec -it single_cell bash
root@localhost:/home/app/webapp# rails console
Loading development environment (Rails 4.2.6)
2.3.1 :001 > user = User.find_by(email: 'sanofisc@gmail.com')
 => nil
2.3.1 :002 > user.update(admin: true)
NoMethodError: undefined method `update' for nil:NilClass
        from (irb):2
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
2.3.1 :003 >

**Comment by bistline** [comment]
You need to log in first with that account to create the record.  The documentation for admin accounts says 'Create a user account normally through the UI (using sign-up or Google auth features)', which is a little vague.  Just boot the portal and sign in with the user account you wanted to make an admin.

**Comment by chees01** [comment]
Getting Error: redirect_uri_mismatch.  
![image](https://user-images.githubusercontent.com/33499865/33083531-9aa99a34-cead-11e7-9ece-3f270dafa28f.png)

Here is what I have in Credentials 
![image](https://user-images.githubusercontent.com/33499865/33083346-22585048-cead-11e7-9285-a820523ea25b.png)

I have tried the following, none of them works... 
https://ndhsinnl145.pharma.aventis.com/single_cell/oauth2callback
https://ndhsinnl145.pharma.aventis.com/oauth2callback
https://ndhsinnl145.pharma.aventis.com/single_cell

Thanks for your help,
Esther

**Comment by bistline** [comment]
If you read the SCP documentation under OAuth Credentials, you'll see the correct form for the redirect URI.  I would urge you to read the 'DEPLOYING A PRIVATE INSTANCE' section thoroughly before continuing.

**Comment by chees01** [comment]
I must be over read that.  Thanks for pointed out…

Esther

**Comment by bistline** [comment]
No problem.  That section was added recently as other developers who were standing up private instances had a lot of issues due to the order of operations in which certain things needed to happen.  If you find something missing or incorrect, please let me know.

**Comment by bgriffen** [comment]
At this step of setting up a private instance:

```
For 'Authorized Javascript Origins', enter the following:
* https://(your hostname)/single_cell
```

I have done exactly that (except using my hostname) but get prompted with the error:

`Invalid Origin: URIs must not contain a path or end with "/".` The offending character is the "/" between `.com` and `single_cell`. How did everyone else proceed past this step since every other private instance would also encounter this issue?

**Comment by jlchang** [comment]
Hi @bgriffen,

Very exciting to hear that you're setting up a private instance! The short (incomplete) answer is to use %2F in lieu of the slash character.

You may want to use a library that will automate such URL encoding tasks. For more details about URL Encoding, see https://www.w3schools.com/tags/ref_urlencode.asp

Please note that Single Cell Portal staff regularly monitors questions submitted via [scp-support@broadinstitute.zendesk.com](mailto:scp-support@broadinstitute.zendesk.com). I recommend that you submit any follow-on questions through that channel to ensure that we receive your inquires in a timely manner.

Regards,
Jean

Single Cell Portal team

**Comment by bgriffen** [comment]
Unfornately, that does not work either. Same error, with URL encoding as well.

<img width="494" alt="Screen Shot 2022-09-20 at 10 30 30 am" src="https://user-images.githubusercontent.com/2667869/191142453-76081ae1-7400-4129-8772-4d529e7b2b09.png">

<img width="493" alt="Screen Shot 2022-09-20 at 10 32 08 am" src="https://user-images.githubusercontent.com/2667869/191142462-87d7861e-9f7c-49bb-9195-bdfff3540f45.png">

**Comment by bistline** [comment]
@bgriffen

Apologies - for JavaScript origins, only the domain should to be entered, such as https://your-domain.com or https://www.your-domain.com.  It appears our README is incorrect in this section.  I'll open up a PR to get that corrected.  Sorry!

Jon
Single Cell Portal Team
