### ISSUE TITLE
The container is up and running without delayed_job.3.log & delayed_job.4.log

### ISSUE THREAD

**Issue by chees01** [broadinstitute/single_cell_portal_core#52]
The container is up and running with the follow error, how do I fix it?  Thanks for your help, Esther

*** Running /etc/my_init.d/02_rails_startup.bash...
*** CLEARING TMP CACHE ***
*** COMPLETED ***
*** ROLLING OVER LOGS ***
/home/app/webapp/bin/cycle_logs.rb:21:in `rename': No such file or directory @ rb_file_s_rename - (log/delayed_job.3.log, log/delayed_job.4.log) (Errno::ENOENT)
        from /home/app/webapp/bin/cycle_logs.rb:21:in `block (2 levels) in <main>'
        from /home/app/webapp/bin/cycle_logs.rb:19:in `each'
        from /home/app/webapp/bin/cycle_logs.rb:19:in `block in <main>'
        from /home/app/webapp/bin/cycle_logs.rb:13:in `downto'
        from /home/app/webapp/bin/cycle_logs.rb:13:in `<main>'
*** COMPLETED ***

**Comment by bistline** [comment]
So I'm unable to reproduce that error by removing log files, although it's not really an issue, per se.  The portal will run without any problems, it's just that it's trying to roll over old log files and isn't finding them (although the way the code is written, it should only operate on log files it finds - there are no hard-coded assumptions about filenames.  I'm perplexed as to how this is actually happening).

Regardless, I put in a check to the script to make sure that the log file exists before trying to rename or remove.  You can do a pull from master to get that fix.
