### ISSUE TITLE
Getting "Firecloud workspce assignment failed..." on creating the first study on our private instance....

### ISSUE THREAD

**Issue by chees01** [broadinstitute/single_cell_portal_core#56]
![image](https://user-images.githubusercontent.com/33499865/33335212-684317cc-d43a-11e7-89dd-1159a9b9a7d1.png)

**Comment by bistline** [comment]
So I'm unable to reproduce this locally on master - I can create new studies from existing project workspaces.  The only reason that I can think of that the service account would be unable to find the workspace is if it's not a member of the billing project in FireCloud, or hasn't been registered as a user yet.

How did you create the billing project you're using?  If you created the project in FireCloud directly, you will need to manually add your service account to the billing project before it can create or modify workspaces inside it on your behalf.  Also, if you didn't register your service account as a FireCloud user, you won't be able to perform any study admin actions inside the portal until you do so.  That has to happen first, in fact.

Take a look at the sections 'Registering your Service Account as a FireCloud user' and 'Creating a FireCloud Project' in the README and see if you perhaps skipped a step.

**Comment by chees01** [comment]
I am able to create new study now after add the service account to the billing project…

Thanks for your help…

Esther

**Comment by bistline** [comment]
Great - glad it was straightforward.
